name: Code coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codecov:
    container:
      image: swift:5.4
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test --enable-code-coverage --show-codecov-path
        id: run_tests
      - name: Codecov
        uses: codecov/codecov-action@v2.0.3
        with:
          flags: unittests
          file: ${{steps.run_tests.outputs}}
          os: macos
