name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          pwd
          ls -la
          COD_COV=$(swift test --enable-code-coverage --show-codecov-path)
          ls -la
          cat $COD_COV
          echo '::set-env name=COD_COV::$COD_COV'
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: $COD_COV
          flags: unittests
          name: codecov-umbrella
