name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: COVERAGE_FILE=$(swift test --enable-code-coverage --show-codecov-path)
        id: run_tests
      - name: Print
        run: echo $COVERAGE_FILE
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: $COVERAGE_FILE
          flags: unittests
          name: codecov-umbrella
