name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test --enable-code-coverage --show-codecov-path
        id: run_tests
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /Users/runner/work/DependencyInjection/DependencyInjection/.build/x86_64-apple-macosx/debug/codecov/DependencyInjection.json
          flags: unittests
          name: codecov-umbrella
