name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test --enable-code-coverage --show-codecov-path
        id: run_tests
      - name: Print
        run: ${{steps.run_tests.outputs}}
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{steps.run_tests.outputs}}
          flags: unittests
          name: codecov-umbrella
