name: Code coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codecov:
    container:
      image: swift:5.3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --enable-code-coverage
    - uses: mattpolzin/swift-codecov-action@0.6.0
      with:
        MINIMUM_COVERAGE: 98
